---
- name: Install iodine
  apt: pkg=iodine state=present

- name: install config
  template:
    src=iodine.default.j2
    dest=/etc/default/iodine
  notify:
    - restart iodine

- name: start iodined server
  service: name=iodined enabled=yes state=started
